name: Build and deploy app to Azure Web App

on:
  workflow_dispatch:
    inputs:
     environment:
        type: environment
        description: Select the environment

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    name: Build and Deploy Job
    steps:
      - name: Hello world
        run: echo Hello world $REACT_APP_BACKEND_URI !
        env:
          REACT_APP_BACKEND_URI: ${{ vars.REACT_APP_BACKEND_URI }}
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_MEADOW_025E14703 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          REACT_APP_BACKEND_URI: ${{ vars.REACT_APP_BACKEND_URI }}
